version: '2'
services:

  postgres:
    image: postgres:9.5.2
    env_file: ./docker/.env-postgres.test

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.1.2
    environment:
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
    ports: ["9200:9200"]

  sut:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: [postgres, elasticsearch]
    links: [postgres, elasticsearch]
    working_dir: /usr/src/app
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 20s -wait http://elasticsearch:9200 -timeout 120s
    command: ./docker/cmd-test.sh
    env_file: ./docker/.env.test
    restart: "no"
