version: '2'
services:

  postgres:
    image: postgres:9.5.2
    env_file: ./docker/.env-postgres

  redis:
    image: redis:3.2
    ports: ["6379:6379"]

  webserver:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on: [postgres]
    links: [postgres]
    working_dir: /usr/src/app
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 20s
    command: ./docker/cmd-webserver.sh
    ports: ["8000:8000"]
    env_file: ./docker/.env
    restart: "always"

  enrolment_worker:
    build:
      context: .
      dockerfile: Dockerfile-enrolment_worker
    depends_on: [webserver]
    links: [postgres]
    working_dir: /usr/src/app
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 20s
    command: ./docker/cmd-enrolment_worker.sh
    env_file: ./docker/.env
    restart: "always"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile-celery_worker
    depends_on: [redis]
    links: [postgres, redis]
    working_dir: /usr/src/app
    entrypoint: dockerize -wait tcp://redis:6379 -timeout 20s
    command: ./docker/cmd-celery_worker.sh
    env_file: ./docker/.env
    restart: "always"
